{{
    config(
        tags=['parcels']
    )
}}

select
    objectid as obj_id,
    parcel as parcel_id,
    x_ref_parcel as site_parcel_id,
    address as parcel_address,
    epoch_ms(CAST(date_parcel_changed AS BIGINT)) as date_parcel_changed,
    property_class,
    property_use,
    assessment_area,
    area_name,
    more_than_one_build,
    home_style,
    year_built,
    bedrooms,
    full_baths,
    half_baths,
    total_living_area,
    first_floor,
    second_floor,
    third_floor,
    above_third_floor,
    finished_attic,
    basement,
    finished_basement,
    exterior_wall1 as exterior_wall_1,
    exterior_wall2 as exterior_wall_2,
    fireplaces,
    central_air,
    partial_assessed,
    assessed_by_state,
    current_land as current_land_value,
    current_impr as current_improvement_value,
    current_total as current_total_value,
    previous_land,
    previous_impr,
    previous_total,
    net_taxes,
    special_assmnt as special_assessment,
    other_charges,
    total_taxes,
    lot_size,
    frontage_street,
    water_frontage,
    tif_district,
    tax_school_dist,
    elementary_school,
    middle_school,
    high_school,
    ward,
    state_assembly_district,
    refuse_district,
    refuse_url,
    previous_land2 as previous_land_2,
    previous_impr2 as previous_impr_2,
    previous_total2 as previous_total_2,
    alder_district,
    epoch_ms(cast(assessment_change_date as bigint)) as assessment_change_date,
    building_district,
    capitol_fire_district,
    epoch_ms(cast(date_added as bigint)) as date_added,
    deed_page,
    deed_restriction,
    deed_volume,
    electrical_district,
    env_health_district,
    exemption_type,
    fire_district,
    flood_plain,
    heating_district,
    illegal_land_division,
    landscape_buffer,
    local_historical_dist,
    lot_depth,
    lot_number,
    lot_type1 as lot_type_1,
    lot_type2 as lot_type_2,
    lot_width,
    national_historical_dist,
    owner_occupied,
    epoch_ms(cast(parcel_change_date as bigint)) as parcel_change_date,
    parcel_code,
    pending,
    planning_district,
    plumbing_district,
    police_district,
    police_sector,
    previous_class,
    property_use_code,
    railroad_frontage,
    senate_district,
    supervisor_district,
    total_dwelling_units,
    type_water_frontage,
    zoning_all,
    house_nbr,
    street_dir,
    street_name,
    street_type,
    unit,
    epoch_ms(cast(property_change_date as bigint)) as property_change_date,
    max_construction_year,
    x_coord,
    y_coord,
    geometry as geom,
    year as parcel_year
from {{ source('arcgis','madison_parcels') }}
where obj_id <> 79239 --Duplicate record from source system parcel 070913330018